### ISSUE TITLE
PHP MySQL library version 10.1.21-MariaDB differs from your MySQL server version 5.6.xx

### ISSUE THREAD

**Issue by daruma8** [phpmyadmin/docker#106]
I got this warning at the bottom of phpmyadmin.
is it all right?
if not, how can I change the lib for MySQL 5.6?

**Comment by nijel** [comment]
AFAIK you would have to recompile Alpine to use that. Pretty much every Linux distribution has switched to MariaDB because MySQL upstream being quite unfriendly to Linux distributions.

This is really problematic area, as the protocol compatibility should be kept, but in past even different MySQL versions behaved wrongly under certain circumstances. Anyway with todays mixture of MariaDB and MySQL in the real world, this warning makes little sense as people are usually not really in the position to fix this.

You can get rid of the warning by setting [$cfg['ServerLibraryDifference_DisableWarning']](https://docs.phpmyadmin.net/en/latest/config.html#cfg_ServerLibraryDifference_DisableWarning) in the [user configuration](https://docs.phpmyadmin.net/en/latest/setup.html#customizing-configuration).

I've just proposed to remove this warning upstream in https://github.com/phpmyadmin/phpmyadmin/pull/13020

**Comment by nijel** [comment]
JFYI: The warning will be gone in 4.7.0.
