### ISSUE TITLE
latest not being updated

### ISSUE THREAD

**Issue by casperbiering** [phpmyadmin/docker#158]
The "lastest" build on docker hub does not container the critical security fix for PMASA-2018-2 neither the fix for "Warning about TempDir in 4.8.0 image #156".

Is it possible to get it updated? Thanks.

**Comment by ibennetch** [comment]
Thanks for calling this to our attention.

The problem was related to how we label security fixes (4.8.0.1-1) which is seen by Docker as an older release than version 4.8.0-2.

If you could, please confirm that the fix is now included (your Dockerfile should include `ENV VERSION 4.8.0.1`).

I believe this is the first time such a situation has occurred since we offer a Docker image and I've adjusted our build documentation to note the problem.

**Comment by casperbiering** [comment]
It works flawlessly now - thanks for the quick response.
