### ISSUE TITLE
question: how can i add phpmyadmin to my existing webserver?

### ISSUE THREAD

**Issue by mytvpro** [phpmyadmin/docker#315]
this is what i have tried but i am clearing missing some things. i have an existing webserver which has self-signing, auto-renewing ssl. i need to add phpmyadmin and mysql for new services.

![image](https://user-images.githubusercontent.com/47206457/100120532-0916a700-2e46-11eb-8416-3d68438f600b.png)

**Comment by mytvpro** [comment]
wait what i have works 😂

**Comment by mytvpro** [comment]
ok i have a probem. cant use 8080 because ssl on for the domain and nginx is already using 443

**Comment by mytvpro** [comment]
i took out the port mapping hoping it would somehow know from being linked to the ngnix container but i dont know how to pull up the ui presently and probably its wrong...

![image](https://user-images.githubusercontent.com/47206457/100133783-34ed5900-2e55-11eb-82b5-8cf495d27639.png)

**Comment by mytvpro** [comment]
guess im way over my head. nginx + cerbot + php was working for my purposes. i cant figure out how to add phpmyadmin to the mix and still need to add mysql as well...

**Comment by ibennetch** [comment]
We are definitely not the best resource for helping you through debugging Docker, but I can give a few hints based on my understanding. Also, please post your configuration files as text rather than images, so we can test things ourselves and don't have to retype them.

nginx presents the ports externally, so you shouldn't need the ports statement for anything other than nginx. You do have to configure nginx to proxy the phpMyAdmin connection, though. Perhaps you're already doing that in ./data/nginx, but you haven't posted the configuration file from there so I'm not sure. You'll probably also need to restart nginx, I may be wrong but I thought any changes you make require a restart. The command line you've defined seems unnecessarily complex; is there a particular reason for it?

When I have problems, I like to cheat and `docker-compose exec` to bash (or sh, or whatever shell comes with the image) and poke around to manually look at what's going on. Also `docker-compose logs` is often invaluable for seeing what errors are being thrown.

What exactly is the problem or error message you're seeing right now?

**Comment by mytvpro** [comment]
i really do appeciate the length you went to there to help. i can see the issue is my lack of understanding of docker-compose than it is how to install phpmyadmin. as it turns out i was told i would need phpmyadmin for this project but in fact the only thing i need to do is import a db wont be needing any other direct access. i am sorry for adding clutter. i will add mariadb to the compose which should be straightforward and be on my way. thank you for your time
