### ISSUE TITLE
[discussion] phpMyAdmin & docker & PHP8

### ISSUE THREAD

**Issue by qeepcologne** [phpmyadmin/docker#325]
are there any blockers with pma on php8? php8 is available for both debian and alpine.
I am using pma 5.0.4 (centos8 + remi repo) on php 8.0.2 without any problems.
Is it possible to upgrade the image or should we create a separate image?

**Comment by ibennetch** [comment]
This is a good issue to bring up.

5.0.4 has a few lingering warnings that should be resolved when I release phpMyAdmin 5.1 in the next day or two. So we definitely weren't ready for PHP 8 until now. Since 7.4 is still very much supported by the PHP community, I haven't seen a need for switching our image over to PHP 8 yet. Is this causing you some inconvenience?

I'm not in a huge rush to switch, but also don't want to get stuck behind for no good reason. Since phpMyAdmin is ready, I'd say we can switch for the release of the next version, phpMyAdmin 5.2. Since 5.1.0 is expected very soon, I'd rather not switch the Docker image now and rush it through.

How does that sound?

**Comment by williamdes** [comment]
I agree, we are quite ready, but rushing would not be a good idea :)
Could you let me know what would be the benefits of switching the image to php8?

**Comment by qeepcologne** [comment]
normally i try docker version on staging, before i put things in production (non-docker). In that case production server runs multiple things, update requirement is not from pma, but it's good to know/test if pma will break or have major issues on php8).
For me docker image is useful when it's bleeding edge.

**Comment by williamdes** [comment]
Oh okay, interesting feedback

You can try our latest version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#devel) and it is compatible with PHP 8.
5.1 will be released soon and Docker will have it afterwards

**Comment by williamdes** [comment]
5.1.0 is out on Docker 🚀 

https://github.com/phpmyadmin/docker/commit/3d8c2ba403fa091a19c6f16762d50663e57f8969

**Comment by williamdes** [comment]
I think we can schedule the switch before 5.2.x series
@J0WI what would be your recommendation ?

**Comment by J0WI** [comment]
+1 for switching with the next release

**Comment by ibennetch** [comment]
Since PHP 7.4 ends active support in three months, I suggest that we switch this to 8.0 sooner rather than later.

Also, I have considered that we don't need to tie this to the phpMyAdmin 5.2.0 release, since the main phpMyAdmin version doesn't depend on any specifics in Docker. So bumping Docker wouldn't need to affect or depend on the feature release of PMA.

**Comment by williamdes** [comment]
Thanks for the feedback, will be bumping the version before 5.1.2 and testing it

**Comment by qeepcologne** [comment]
is it possible to release it?

**Comment by williamdes** [comment]
> is it possible to release it?

On next release of phpMyAdmin, that should be soon normally
I would recommend to subscribe to release notifications on this repository

**Comment by ibennetch** [comment]
The latest Docker images use PHP 8.0 (starting with release 5.1.2, although 5.1.3 has just been published).

Thank you

**Comment by qeepcologne** [comment]
thanks for releasing, but meanwhile php 8.0 is has reached 15/24 months of support phase and we should move on to php 8.1.

**Comment by ibennetch** [comment]
Indeed, 8.1 is on my to do list for the next set of builds. Thanks.
